spring:
  datasource:
    url: jdbc:postgresql://${DB_URL}
    username: ${DB_USER}
    password: ${DB_PASS}
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true
    database: mysql
    database-platform: org.hibernate.dialect.MySQLDialect
logging:
  level:
    org.springframework.jdbc.datasource: DEBUG
    org.springframework.boot.autoconfigure.jdbc: DEBUG
    org.springframework.orm.jpa: DEBUG